Removed conf lightdm

diff --git a/pkgbuild/pkgbuild.install b/pkgbuild/pkgbuild.install
--- a/pkgbuild/pkgbuild.install
+++ b/pkgbuild/pkgbuild.install
@@ -2,38 +2,46 @@
 # This file contains scripts that are executed at different stages of package installation/upgrade/removal
 
 # Function executed before package installation
-pre_install() {
-    # Verifica se os pacotes antigos E o LightDM estão instalados
-    if (pacman -Q lightdm-webkit2-greeter &>/dev/null || pacman -Q lightdm-webkit2-theme-community &>/dev/null) && pacman -Q lightdm &>/dev/null; then
-        touch /tmp/comm_install_slick
-    fi
-}
+# pre_install() {
+#     echo "Preparing to install the package..."
+    # Example: Check for system dependencies
+    # if ! command -v required_command &> /dev/null; then
+    #     echo "Error: required_command not found. Please install it before continuing."
+    #     exit 1
+    # fi
+# }
 
 # Function executed after package installation
-post_install() {
-    # Instala o slick-greeter apenas se o LightDM e os pacotes antigos existiam
-    if [ -f /tmp/comm_install_slick ]; then
-        pacman -S --noconfirm lightdm-slick-greeter
-        rm /tmp/comm_install_slick
-    fi
+# post_install() {
+#     echo "Configuring the package after installation..."
+    # Example: Create a configuration directory
+    # mkdir -p /etc/mypackage
+    # chmod 755 /etc/mypackage
 
-    # Configura o LightDM para usar o slick-greeter
-    if grep -q '^\[Seat:\*\]' /etc/lightdm/lightdm.conf; then
-        sed -i '/^\[Seat:\*\]/,/^$/ s/^#*\s*greeter-session\s*=.*/greeter-session=lightdm-slick-greeter/' /etc/lightdm/lightdm.conf
-    else
-        echo -e "\n[Seat:*]\ngreeter-session=lightdm-slick-greeter" >> /etc/lightdm/lightdm.conf
-    fi
-}
+    # Example: Start a service
+    # systemctl enable myservice.service
+    # systemctl start myservice.service
+# }
 
 # Function executed before package upgrade
-pre_upgrade() {
-    pre_install
-}
+# pre_upgrade() {
+#     echo "Preparing to upgrade the package..."
+    # Example: Backup configuration files
+    # cp /etc/mypackage/config.conf /etc/mypackage/config.conf.bak
+# }
 
 # Function executed after package upgrade
-post_upgrade() {
-    post_install
-}
+# post_upgrade() {
+#     echo "Finalizing package upgrade..."
+    # Usually, post_install is called here to ensure
+    # all post-installation configurations are applied
+#     post_install
+
+    # Example: Check and update configuration files
+    # if [ -f /etc/mypackage/config.conf.pacnew ]; then
+    #     echo "New configuration file available. Please review /etc/mypackage/config.conf.pacnew"
+    # fi
+# }
 
 # Function executed before package removal
 # pre_remove() {
